language: node_js
cache: yarn
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
notifications:
  email: false
script:
  - npm run lint:whitespace
  - npm run lint:prettier
  - npm run lint:js
  - npm run test:coverage
